### PR TITLE
common: add support for token netrc

### PR DESCRIPTION
**Pull request by kyrofa**
The current netrc logic has two limitations. First of all, it assumes that when authentication is required the server will return HTTP 401, which isn't always the case (e.g. gitlab returns 404 to prevent leaking the existence of a file). Second, there are servers that don't support basic auth, and instead only support tokens (e.g. gitlab again). This PR fixed both of these issues by checking against a return code list instead of just 401, as well as adding support for netrc files that only contain a password (this makes it work the same way as git).

### CODE REVIEW

**Comment by kyrofa** [comment]
@dirk-thomas, @wjwwood, any chance this could get a pair of eyes or two?

**Comment by wjwwood** [comment]
I don't have time right now with both the Foxy and Noetic releases in flight. Maybe if you ping me back in June I can have a look. Because I would also need to release this and therefore have a look at all the other open issues and pull requests.

There might be someone else in @vcstools/maintainers that has time before then.

**Comment by dirk-thomas** [comment]
I am sorry but I don't maintain this repo.

The Noetic instructions will likely recommend to use `vcstool` instead which is actively maintained and also used in ROS 2.

**Comment by kyrofa** [comment]
> The Noetic instructions will likely recommend to use vcstool

That's helpful to know, thank you, I'll make sure that supports this as well.

**Comment by kyrofa** [comment]
Proposed vcstool support over on https://github.com/dirk-thomas/vcstool/pull/128 . This PR would still be useful for pre-noetic distros though.

**Comment by dirk-thomas** [comment]
> This PR would still be useful for pre-noetic distros though.

It might be worth checking - once we have the Noetic instructions solid and tested - if updating the instructions from previous distros is an option. Simply because there is no activity here and something like Melodic is still supported for 3 years.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.

**Pull request closed without merging**
