### PR TITLE
Add Suite3 option with Ubuntu Focal

### PR DESCRIPTION
**Pull request by sloretz**
Mimicking ros-infrastructure/catkin_pkg#271

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]

**Comment by sloretz** [comment]
@wjwwood since it's been a while, I'm wondering if we should deprecate and not release vcstools, wstool, and rosinstall into Ubuntu Focal. Missing those dependencies hasn't blocked anything so far, and I don't see any use of `python-vcstools`, `python-wstool`, and `python-rosinstall` in the [Melodic package.xml cache](http://repositories.ros.org/rosdistro_cache/melodic-cache.yaml.gz).

If so, this PR and #160 can be closed.

**Comment by wjwwood** [comment]
`wstool` is used in this documentation, I don't know if it will be the same for Noetic:

https://wiki.ros.org/melodic/Installation/Source#Create_a_catkin_Workspace

`wstool` depends on `vcstools`. I'm not sure about `rosinstall`, I know that it shares implementation details with `wstool`, but I don't know where it is used in the documentation at this time, but I would guess there are still plenty of places it is used.

**Comment by sloretz** [comment]
> wstool is used in this documentation, I don't know if it will be the same for Noetic:

I replaced it with `vcstool` in the same section on the Noetic page: https://wiki.ros.org/noetic/Installation/Source#Create_a_catkin_Workspace

Anywhere else you're aware of it being used?

**Comment by wjwwood** [comment]
No, not without going through most of the wiki.ros.org docs, I couldn't say. I don't mind if we release this or not to be honest, but I expect there are still plenty of places that wstool is mentioned that will just stop working.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.

**Pull request closed without merging**
