### PR TITLE
Fix python3 github chunked download & Mock server tar test

### PR DESCRIPTION
**Pull request by tkruse**
this includes and supercedes #140 
@kartikmohta: plz review the testcode changes

### CODE REVIEW

**Comment by kartikmohta** [comment]
@tkruse Looks great! Thanks for putting in the effort to add the tests.

**Comment by tkruse** [comment]
Feel free to ask for votes on this issue in the ros forums if you believe this should be fixed urgently. I don't know how many users are affected by this bug.

**Comment by ShreyasSkandan** [comment]
I'm trying to install ROS using wstools and I'm facing the same problem. I'm not sure how to fix this problem since I didn't explicitly install vcstools. 

I run the following commands:
`
rosinstall_generator ros_comm --rosdistro melodic --deps --tar > melodic-ros_comm.rosinstall
wstool init -j8 src melodic-ros_comm.rosinstall
`

And get a bunch of errors like
`
[genmsg] Fetching https://github.com/ros-gbp/genmsg-release/archive/release/melodic/genmsg/0.5.11-0.tar.gz (version genmsg-release-release-melodic-genmsg-0.5.11-0) to /home/nvidia/ros_py35/src/genmsg
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]
[cmake_modules] Done.
`
and 
`
Error processing 'std_msgs' : [std_msgs] Checkout of https://github.com/ros-gbp/std_msgs-release/archive/release/melodic/std_msgs/0.5.11-0.tar.gz version std_msgs-release-release-melodic-std_msgs-0.5.11-0 into /home/nvidia/ros_py35/src/std_msgs failed.
`

I'm not sure if the two are related but this thread seems relevant to my issue. Any help is appreciated.

**Comment by tkruse** [comment]
You'd need to install vcstools and wstool from source, using the branch of the fix.

    mkvirtualenv wstool
    git clone https://github.com/tkruse/vcstools
    cd vcstools
    git checkout mock_server_tar_test
    python setup.py develop
    cd ..
    git clone https://github.com/vcstools/wstool
    cd wstool
    python setup.py develop
    wstool --help

Also feel free to suggest a new release on ros-users.

**Comment by ShreyasSkandan** [comment]
> You'd need to install vcstools and wstool from source, using the branch of the fix.
> 
> ```
> mkvirtualenv wstool
> git clone https://github.com/tkruse/vcstools
> cd vcstools
> git checkout mock_server_tar_test
> python setup.py develop
> cd ..
> git clone https://github.com/vcstools/wstool
> cd wstool
> python setup.py develop
> wstool --help
> ```
> 
> Also feel free to suggest a new release on ros-users.

Fantastic, it works now. Thanks!

**Comment by ffurrer** [comment]
also worked for me, thanks :)

**Comment by 130s** [comment]
This has got sufficient upvotes to move forward IMO.

**Comment by 130s** [comment]
I believe @tkruse is the main maintainer. This is his PR but @kartikmohta was asked for the review and I think he already approved https://github.com/vcstools/vcstools/pull/141#issuecomment-421433000. Without knowing the review policy on this repo, I think this is ready for merge.

https://github.com/vcstools/vcstools/pull/144#issuecomment-427551430 suggests that this PR might block CI for other PRs on this including https://github.com/vcstools/vcstools/pull/144 (and #144 has been causing issues in our team every day).

Thank you!

**Comment by tkruse** [comment]
@130s I have never released this repo. If you can, feel free to merge.

**Comment by 130s** [comment]
@tkruse I see. Then, I don't have a write access.

@tfoote @wjwwood You two are the most active committers. #77 makes `wstool` hard to use in some situation. #144 is suggested to fix that. Then, https://github.com/vcstools/vcstools/pull/144#issuecomment-427551430 suggests that this PR should be merged first. Could any of you can take care of these PRs?

**Comment by tkruse** [comment]
@130s : It seems I can merge PRs, though I usually did not. So if you know how to release, I am willing to do the merge while I can.

**Comment by 130s** [comment]
Friendly ping @clalancette for the review.

**Pull request merged**
