### PR TITLE
Add fake identity for VCSs

### PR DESCRIPTION
**Pull request by jspricke**
This makes the unit tests self contained.

### CODE REVIEW

**Comment by wjwwood** [comment]
@jspricke can you rebase this since https://github.com/vcstools/vcstools/pull/124 was merged? It should get the CI back in working order. I would rebase it for you on this pr, but that last two times I tried that it ended up closing the original pr.

**Comment by jspricke** [comment]
Same as for https://github.com/vcstools/wstool/pull/104, reference Debian build log: https://buildd.debian.org/status/fetch.php?pkg=ros-vcstools&arch=all&ver=0.1.39-4&stamp=1500395896&raw=0

**Comment by jspricke** [comment]
@wjwwood could you fix Travis here as well?

**Comment by wjwwood** [comment]
@jspricke I believe it is working here, because the tests are laid out in a more conventional way (everything in files starting with test_ in the folder test).

**Comment by jspricke** [comment]
I have no idea why this fails, but doesn't look related to my changes. @wjwwood do you have time to fix it?

**Comment by wjwwood** [comment]
Ok, I fixed travis in another pr and rebased this one. Any failures here ought to be related to these changes now.

**Comment by jspricke** [comment]
Thanks for the work. Anything I need to do to get this merged?

**Comment by wjwwood** [comment]
Nope looks good. Thanks.

**Pull request merged**
