### PR TITLE
Minor changes, prepare for vcstools/wstool#71

### PR DESCRIPTION
**Pull request by tkruse**

### CODE REVIEW

**Comment by tkruse** [comment]
@wjwwood, @dirk-thomas please review (no hurry). Adding @dirk-thomas because of vcstools/wstool#71

**Comment by wjwwood** [comment]
Changes and new tests look good to me, but there are failing style tests. I'll merge with passing CI.

**Comment by tkruse** [comment]
should be ok now. Was originally just pep8 flaws. I also had to change travis config to keep 'coverage' package below version4, because of py3.2 incompatibility. An alternative would be not to test against python 3.2 in travis anymore.

**Comment by wjwwood** [comment]
I've stopped testing Python 3.2 and 3.3 in many of my repositories, and just test 3.4 now.

**Pull request merged**
