### PR TITLE
Workaround for GitHub issue that randomly drops revision info from tarball directory names

### PR DESCRIPTION
**Pull request by KenYN**
Works around https://github.com/vcstools/vcstools/issues/147

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
As someone who's been bitten by this, I fully appreciate the effort @KenYN.

However (and this is going to be pedantic, so my apologies in advance): can we please refrain from using terminology such as "fixes" and "addresses"? Words like that imply that this is an issue on "our side" and that something is wrong in `wstool`, while in fact, it would appear GH has changed something or something is broken in the API / backend that generates those tarballs.

At best, the changes proposed in this PR are a work-around and personally I doubt they should be accepted. Using this as a local, temporary work-around is fine, but I'd much rather wait for the resolution of https://github.com/vcstools/vcstools/issues/147 based on GH support.

**Comment by chrisl8** [comment]
@KenYN I have run `wstool` with your patch several times now on the melodic desktop_full bundle, and it works great!
I have only fully compiled the source from the output once, but that did also work fine.

@gavanderhoorn I would agree if this was a documented GitHub feature, but even if they revert the behavior of their system, what guarantee do we have that they will not do this again?
Because this is not a documented feature that GitHub provides, I would prefer to to see vcstools/wstool be as robust as possible to all of the various formats GitHub has shown us that it might provide.

**Comment by tkruse** [comment]
We have the same guarantee about this GitHub bug not coming back as for any other GitHub bug.
I believe GitHub giving random foldernames on different days for the same tar URL cannot be anything else than a bug.

The wstool contract is simple, you give the URL of a tarball and the name of a subfolder as "version", and wstool will download and extract.

The workaround tries some fallback subfolder name which the user did NOT specify. That is very irrate behavior for any tool, and documenting that feature in wstool will also be ugly. Keeping that workaround just because GitHub might add this bug again does not seem reasonable.

**Comment by tkruse** [comment]
Actually, we could instead try to make this a reasonable feature instead. Such as: when no version string is given, wstool will expect a single subfolder in the tarball, and extract that.

Or possibly use a magic version key such as "DEFAULT", if passing empty versions causes many problems with our code.

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn I would agree if this was a documented GitHub feature, but even if they revert the behavior of their system, what guarantee do we have that they will not do this again?
> Because this is not a documented feature that GitHub provides, I would prefer to to see vcstools/wstool be as robust as possible to all of the various formats GitHub has shown us that it might provide.

I'm pretty sure this is actually a "documented feature". See the [Get archive link](https://developer.github.com/v3/repos/contents/#get-archive-link) docs in the Github v3 API docs fi.

But tbh I don't feel it's very important whether it's documented or not: until we know what the cause and the reason is for this change in behaviour of GH, it doesn't make much sense to me to start submitting PRs that "fix" the issue.

As @tkruse also commented: it could well be a bug or regression, so it'd make sense to first get some clarity.

**Comment by chrisl8** [comment]
Personally I would just change the code to use whatever folder exists in the tar, rather than trying to guess it ahead of time.

I feel like maybe there is some reason for this guessing ahead of time that I'm not aware of. 
In theory it could be to confirm that we got the version we asked for, but I feel like the fact that it was given to us with  URL that includes the version number is enough. 

Was there some other reason?

**Comment by tkruse** [comment]
This commit touches the code
https://github.com/vcstools/vcstools/commit/bb4775bfe7442e81017bd365da9a8f3542dd61a0
Changing from shell to tar library, but keeping the logic intact.
This commit imported the logic from ros_release:
https://github.com/vcstools/vcstools/commit/a11b2d73141902cbaa690be0189116de9a023274

ros_release might never have been transitioned from SVN to git, not sure if anyone still has the version history.
All this to say this is very old code, so nobody might remember the reason.

Note that wstool just takes the location of a jar and a string for the subfolder name. The tar name does not have to include a version, and the tar does not have to contain a single folder, right now.

**Comment by KenYN** [comment]
@chrisl8 Great! I'm working with kinetic and https://github.com/containers/buildah (building my own absolute minimal ROS for our own project) so I've not been testing on other releases.

@gavanderhoorn OK, renamed the pull.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.

**Pull request closed without merging**
