### PR TITLE
Clean up shebang and executable warnings

### PR DESCRIPTION
**Pull request by cottsay**
Same routine as ros-infrastructure/rosdep#630, ros-infrastructure/rospkg#159 and ros-infrastructure/rosdistro#125.

### CODE REVIEW

**Comment by tfoote** [comment]
So at least the first file i checked actually has a main and can be run.  src/vcstools/git_archive_all.py which suggests that the shebang and executable bits are valid.

**Comment by cottsay** [comment]
There are two reasons the shebang should be removed from that file:
1. The executable bit is removed when installed as a module on the system, at least the way Ubuntu and Fedora package it through `setuptools`. This renders the shebang completely useless.
    ```
    cottsay@cottsay-box-bionic:~$ ls -alh /usr/lib/python3/dist-packages/vcstools/git_archive_all.py 
    -rw-r--r-- 1 root root 21K Aug 26  2016 /usr/lib/python3/dist-packages/vcstools/git_archive_all.py
    ```
2. The shebang always points to `/usr/bin/env python`, which may be a different interpreter from 
the module itself.
    ```
    cottsay@cottsay-box-bionic:~$ /usr/bin/env python --version
    Python 2.7.15rc1
    cottsay@cottsay-box-bionic:~$ head -1 /usr/lib/python3/dist-packages/vcstools/git_archive_all.py
    #! /usr/bin/env python
    ```

Even after the shebang is removed, the script's `__main__` can still be invoked:
```
cottsay@cottsay-box-bionic:~$ sudo sed '1{/^#!/d}' -i /usr/lib/python3/dist-packages/vcstools/git_archive_all.py
cottsay@cottsay-box-bionic:~$ python3 /usr/lib/python3/dist-packages/vcstools/git_archive_all.py
Usage: git_archive_all.py [-v] [--prefix PREFIX] [--no-exclude] [--force-submodules] [--extra EXTRA1 [EXTRA2]] [--dry-run] OUTPUT_FILE

git_archive_all.py: error: You must specify exactly one output file
```

**Comment by wjwwood** [comment]
@cottsay I'll defer to you and @tfoote on this issue. In the past I've helped with reviews and releases for these repositories, but if you need to make progress on this issue you might need to take up that role temporarily.

**Comment by tkruse** [comment]
merged

**Pull request closed without merging**
