### PR TITLE
add contents of submodules into archive

### PR DESCRIPTION
**Pull request by k-okada**
this is work around for #84

### CODE REVIEW

**Comment by tkruse** [comment]
Coming back to this... 
Possibly we could keep the current call to ```git archive``` when a version is specified, and fail when submodules exist as well. It's not perfect, but might be okay.

**Comment by tkruse** [comment]
also this needs to be rebased, and updated with the latest changes at github.com/Kentzo/git-archive-all

**Comment by k-okada** [comment]
ok, rebased

**Comment by tkruse** [comment]
Sorry, I meant the alternative pull request. So confusing.

**Comment by wjwwood** [comment]
Yeah, I think it would be better to fixup #95 since it won't use `tar` directly.

It's unfortunate that the `tarfile` module in Python doesn't provide a `__main__` which emulates the arguments of `tar`. Then we could just replace `tar` in this pull request with `python -m tarfile`.

**Comment by wjwwood** [comment]
Superseded by https://github.com/vcstools/vcstools/pull/110.

**Pull request closed without merging**
